### ISSUE TITLE
Station chosen!

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework5G2#11]
We, G1, are planning to choose "Sand Island, Midway, United States (MID)" station. What about you guys?

**Comment by pratibha77118** [comment]
Great! Thanks for letting us know.

**Comment by Pranjal-Srivastava-2023** [comment]
We have chosen https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_avi_surface-flask_1_ccgg_month.txt
