### ISSUE TITLE
Who is the maintainer?

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework5G2#12]
Hi @yasmensarhan27 and @Pranjal-Srivastava-2023,
Who is the maintainer for our group 2? Also please assist me what to do in the task 1 for this homework?

**Comment by pratibha77118** [comment]
We need to confirm soon. If no one is maintainer yet. I will be the maintainer for this homework, however I have been the maintainer for many times.

**Comment by pratibha77118** [comment]
@yasmensarhan27 there is no maintainer for our group. Why don't you ask professor to access you as a maintainer?

**Comment by yasmensarhan27** [comment]
why don’t you be the maintainer as you mentioned above.
I can’t be the maintainer
Sorry
