### ISSUE TITLE
Task 1 confusion

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework5G2#13]
Hello @yasmensarhan27 and @Pranjal-Srivastava-2023 
I need few confusions to be cleared out for task one.
1. We read the data from the selected site and find the peaks of values from the data.
2.  We then identify the intervals between peaks and convert them to yearly basis from monthly basis as given in data.
 This is my overview for doing task 1. If I am not able to get it, please assist me what I should be doing?

**Comment by tirthbha** [comment]
What values have you got for the peak and actual frequency, can you share your answer?

**Comment by poojashresthacode** [comment]
What is the unit you have choosen?

**Comment by pratibha77118** [comment]
I chosed cycle/month as the unit.

**Comment by Pranjal-Srivastava-2023** [comment]
cycle/month is the correct unit to choose.
