### ISSUE TITLE
station chosen (ASC)

### ISSUE THREAD

**Issue by LinxuanHu** [ubsuny/23-Homework5G2#14]
we G3 choose Ascension Island, United Kingdom (ASC)

**Comment by poojashresthacode** [comment]
Thanks for updating

**Comment by Pranjal-Srivastava-2023** [comment]
We are using https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_avi_surface-flask_1_ccgg_month.txt
