### ISSUE TITLE
Task 2.

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework5G2#19]
Hello dear all, who is doing task 2 in your group? I need to ask something

**Comment by Mosaddeq107** [comment]
Can you write your confusion? So that we can be enlightened?

**Comment by poojashresthacode** [comment]
In group 1, tirth is doing it. You can also ask him @uarif

**Comment by uarif** [comment]
Yes, I am talking about the cutoff frequency, I took a maximum frequency to be 1, and the filtered the higher frequencies from 0.07 I guess, higher than that, I ignored. Does it make sense to you? @Mosaddeq107

**Comment by uarif** [comment]
> In group 1, tirth is doing it. You can also ask him @uarif

Okay, Thank you .
