### ISSUE TITLE
Task assignment

### ISSUE THREAD

**Issue by yasmensarhan27** [ubsuny/23-Homework5G2#2]
Hello 
This is to discuss which task will be assigned for each one @pratibha77118 @Pranjal-Srivastava-2023

**Comment by Pranjal-Srivastava-2023** [comment]
Hello, @yasmensarhan27 I can take care of the algorithm and unit tests.

**Comment by pratibha77118** [comment]
@yasmensarhan27 & @Pranjal-Srivastava-2023  I will go with task 1.

**Comment by yasmensarhan27** [comment]
The tasks are divided as task1, 2 or 3 
@Pranjal-Srivastava-2023 which task you will go for ?

**Comment by Pranjal-Srivastava-2023** [comment]
> The tasks are divided as task1, 2 or 3 @Pranjal-Srivastava-2023 which task you will go for ?

I will go for task 2 then.

**Comment by yasmensarhan27** [comment]
So, I'm left with task 3 

when will you finish the 1st and 2 parts @Pranjal-Srivastava-2023 @pratibha77118 so I can write the unit test and documentation for them

**Comment by yasmensarhan27** [comment]
kindly let me know in order to organize my work

**Comment by yasmensarhan27** [comment]
!! @pratibha77118 @Pranjal-Srivastava-2023 
please keep in mind that I've proctoring and grading all day on Saturday. Allow me some time to get my task done.

**Comment by pratibha77118** [comment]
@yasmensarhan27 guys i just donot get the idea from where to start? Please assist me so that I can complete it by today?
