### ISSUE TITLE
Nearest value

### ISSUE THREAD

**Issue by tirthbha** [ubsuny/23-Homework5G2#22]
We have 452 number of data points. For the padding, do we need to approach to the nearest of this value as power of 2?

**Comment by poojashresthacode** [comment]
Are the numbers of data points used in the first task different from the second task? I think reshna has used the number of data as power of 2.

**Comment by pratibha77118** [comment]
Ya even if we put more values it will use nearest power of 2 by default.

**Comment by tirthbha** [comment]
@pratibha77118 It is not by default, you have to set that nearest value as power of 2.

**Comment by Pranjal-Srivastava-2023** [comment]
@tirthbha Yes, the nearest value needs to be set.

**Comment by yasmensarhan27** [comment]
@tirthbha 
you can use the slicing to cut off some data to reach the nearest 2^n
