### ISSUE TITLE
Data selection

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G2#32]
Group 4 is using Bermuda data (#12 of the link).

**Comment by sharmistharanit** [comment]
Which one are you guys using?

**Comment by Pranjal-Srivastava-2023** [comment]
@sharmistharanit we are using:
https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_avi_surface-flask_1_ccgg_month.txt

**Comment by Pranjal-Srivastava-2023** [comment]
> Group 4 is using Bermuda data (#12 of the link).

@sharmistharanit Good to know!
