### ISSUE TITLE
Station choice

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework5G2#4]
Which station are we gonna choose for our homework?

**Comment by yasmensarhan27** [comment]
what do you think of this one ?? @pratibha77118 @Pranjal-Srivastava-2023 
flask CO2 
https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_avi_surface-flask_1_ccgg_month.txt

**Comment by pratibha77118** [comment]
@yasmensarhan27 What is the name of this site?

**Comment by pratibha77118** [comment]
St. Croix, Virgin Islands, United States (AVI) Okay this the name. I get it now.

**Comment by Pranjal-Srivastava-2023** [comment]
That will work.
