### ISSUE TITLE
5 new labels

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework5G2#40]
Can the maintainer create 5 new labels, we will all get 1 point :)

**Comment by pratibha77118** [comment]
Sure I can. @Pranjal-Srivastava-2023 I am sorry I am not able to complete task by this wednesday. I talked to professor , he let us to finish by thursday.

**Comment by Pranjal-Srivastava-2023** [comment]
> Sure I can. @Pranjal-Srivastava-2023 I am sorry I am not able to complete task by this wednesday. I talked to professor , he let us to finish by thursday.

@pratibha77118 is the new deadline on Thursday? I didn't know that.

**Comment by pratibha77118** [comment]
@Pranjal-Srivastava-2023 No the deadline is tomorrow. Any group who has completed their task can present tomorrow, I think .
