### ISSUE TITLE
Add figures in repository

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework5G2#48]
Add the output plots in the repository.

**Comment by pratibha77118** [comment]
@Pranjal-Srivastava-2023 can we add the plots you did for task 2 in the documentation part?

**Comment by Pranjal-Srivastava-2023** [comment]
> @Pranjal-Srivastava-2023 can we add the plots you did for task 2 in the documentation part?

@pratibha77118 sure, please add the plots in the documentation.

**Comment by reshnashrestha** [comment]
Exactly, there are no plots. You can add plot for better presentation.

**Comment by yasmensarhan27** [comment]
Hi @Pranjal-Srivastava-2023  you can add them to the repository as .jpg files

and please check the documentation part to see if any thing is missing
