### ISSUE TITLE
Question confusion

### ISSUE THREAD

**Issue by sharmistharanit** [ubsuny/23-Homework5G2#5]
What are we supposed to do to address the task (Write a function that calculates the actual frequency in useful units)? Any help will be appreciated.

**Comment by reshnashrestha** [comment]
Yeah same question

**Comment by Pranjal-Srivastava-2023** [comment]
> What are we supposed to do to address the task (Write a function that calculates the actual frequency in useful units)? Any help will be appreciated.

And also find the peak frequency.
