### ISSUE TITLE
Unit test action improper file referenced

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework5G2#50]
On this line in your unit test https://github.com/ubsuny/23-Homework5G2/blob/2597690425b448e2b57ddcfa84a8ed2c65d3ed94/.github/workflows/Unittesting.yml#L21 you pytest the algorithm you wrote. At this stage, you need to run the actual unit test file you've written instead. I created a pull request addressing this (https://github.com/ubsuny/23-Homework5G2/pull/49) so it should hopefully be a quick fix.

**Comment by yasmensarhan27** [comment]
Pytest and pylint weren't done yet 
they are available now on the main repository
Pytest has passed but the pylint we barely got 8.69/10 

by the way, I'm not the maintainer :D
