### ISSUE TITLE
Task 1 completion

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G2#59]
have you completed the task 1?

**Comment by pratibha77118** [comment]
Ya I think so. What about your's @reshnashrestha ?

**Comment by reshnashrestha** [comment]
I have done it to my best but still not sure with peak frequency one. 
Have you figured it out?

**Comment by reshnashrestha** [comment]
Hey guys you can check out our (group1) work under task1 folder in the main branch.
