### ISSUE TITLE
Peak frequency

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G2#60]
How are you calculating peak frequency?

**Comment by pratibha77118** [comment]
I have almost completed the task. I used fft and have eliminated the data with high frequency part so that I get an value of 2 cycles per year.

**Comment by reshnashrestha** [comment]
Can you show your resultant plot?

**Comment by reshnashrestha** [comment]
I have used scipy.sigmal and imported find.peaks.
