### ISSUE TITLE
Task 1 discussion 

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G2#7]
Who is doing task 1 in this group?

**Comment by yasmensarhan27** [comment]
@pratibha77118 is the responsible for task 1

**Comment by reshnashrestha** [comment]
Oh okay thanks for letting me know. @pratibha77118 have you started any?

**Comment by pratibha77118** [comment]
I am starting now @reshnashrestha . Any idea how to go with task 1.

**Comment by reshnashrestha** [comment]
we have to write a function that calculates the actual frequency in useful units, but I am still figuring this out.
