### ISSUE TITLE
peak frequency and clean up

### ISSUE THREAD

**Issue by reshnashrestha** [ubsuny/23-Homework5G2#71]
Are we supposed to use the clean up data for peak frequency in task 1?

**Comment by tirthbha** [comment]
I think, as mentioned in the task 1, you need to find peaks for the raw data because we are not supposed to do the filtering process in this step.

**Comment by pratibha77118** [comment]
I don't think it is said not to use the clean up data for peak frequency in the task 1. We use it. I can check on the different way you did to find peak frequency.
