### ISSUE TITLE
Deleted 40 commits accidentally.

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework5G2#75]
I accidentally deleted 40 commits due to which all my work got deleted. I again started from scratch and I have almost finished it. but do you guys know how to recover the files if the commits are deleted? I requested for the ticket from the support system of Git Hub, however, it will take a too long time. I would be grateful if any of you know about it.

**Comment by pratibha77118** [comment]
@poojashresthacode thanks for letting me know about it. I  didn't know that you can request for tickect from git hub support system.
