### ISSUE TITLE
data for your group, 

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework5G2#9]
Can I ask which data are you guys taking? I think it should be fine with whatever data we take, right?

**Comment by reshnashrestha** [comment]
Yeah, because there are plenty so its very rare to collide over what we choose.

**Comment by Pranjal-Srivastava-2023** [comment]
@uarif We chose https://gml.noaa.gov/aftp/data/trace_gases/co2/flask/surface/txt/co2_avi_surface-flask_1_ccgg_month.txt
